### ISSUE TITLE
Retornando linha branca no search

### ISSUE THREAD

**Issue by chgsilva** [miguelarauj1o/ipmt#1]
Quando eu coloco o seguinte comando, 
$ ./bin/ipmt search lines README.idx
o programa imprime três linhas brancas.
PS: o README.idx é o README.txt indexado.

**Comment by chgsilva** [comment]
ps: foi no mac

**Comment by paulolieuthier** [comment]
@chgsilva por favor, tenta de novo! :+1:

**Comment by chgsilva** [comment]
@paulolieuthier ta certinho agora! 👍🏽
